In [1]:
# Import Dependencies
import pandas as pd

In [2]:
csv_path = "Resources/Happiness_2017.csv"
happiness_df = pd.read_csv(csv_path)
happiness_df.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [5]:
# Sorting the DataFrame based on "Freedom" column
# Will sort from lowest to highest if no other parameter is passed
freedom_df = happiness_df.sort_values("Freedom")
freedom_df.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
139,Angola,140,3.795,3.951642,3.638358,0.858428,1.104412,0.049869,0.000000,0.097926,0.069720,1.614482
129,Sudan,130,4.139,4.345747,3.932253,0.659517,1.214009,0.290921,0.014996,0.182317,0.089848,1.687066
144,Haiti,145,3.603,3.734715,3.471285,0.368610,0.640450,0.277321,0.030370,0.489204,0.099872,1.697168
153,Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574

In [6]:
# To sort from highest to lowest, ascending=False must be passed in
freedom_df = happiness_df.sort_values("Freedom", ascending=False)
freedom_df.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
46,Uzbekistan,47,5.971,6.065538,5.876463,0.786441,1.548969,0.498273,0.658249,0.415984,0.246528,1.816914
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
128,Cambodia,129,4.168,4.278518,4.057483,0.601765,1.006238,0.429783,0.633376,0.385923,0.068106,1.042941
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707

In [7]:
# It is possible to sort based upon multiple columns
family_and_generosity_df = happiness_df.sort_values(
    ["Family", "Generosity"], ascending=False)
family_and_generosity_df.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
14,Ireland,15,6.977,7.043352,6.910649,1.535707,1.558231,0.809783,0.573110,0.427858,0.298388,1.773869
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
46,Uzbekistan,47,5.971,6.065538,5.876463,0.786441,1.548969,0.498273,0.658249,0.415984,0.246528,1.816914
7,New Zealand,8,7.314,7.379510,7.248490,1.405706,1.548195,0.816760,0.614062,0.500005,0.382817,2.046456

In [8]:
# The index can be reset to provide index numbers based on the new rankings.
new_index_df = family_and_generosity_df.reset_index(drop=True)
new_index_df.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
1,Ireland,15,6.977,7.043352,6.910649,1.535707,1.558231,0.809783,0.573110,0.427858,0.298388,1.773869
2,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
3,Uzbekistan,47,5.971,6.065538,5.876463,0.786441,1.548969,0.498273,0.658249,0.415984,0.246528,1.816914
4,New Zealand,8,7.314,7.379510,7.248490,1.405706,1.548195,0.816760,0.614062,0.500005,0.382817,2.046456

In [11]:
family_and_generosity_df = happiness_df.sort_values("Dystopia.Residual")
family_and_generosity_df.head(20)

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
141,Botswana,142,3.766,3.874123,3.657877,1.122094,1.221555,0.341756,0.505196,0.099348,0.098583,0.377914
119,Sri Lanka,120,4.440,4.553447,4.326553,1.009850,1.259976,0.625131,0.561213,0.490864,0.073654,0.419389
150,Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
70,"Hong Kong S.A.R., China",71,5.472,5.549594,5.394406,1.551675,1.262791,0.943062,0.490969,0.374466,0.293934,0.554633
152,Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
131,Ukraine,132,4.096,4.185410,4.006590,0.894652,1.394538,0.575904,0.122975,0.270061,0.023029,0.814382
104,Bulgaria,105,4.714,4.803695,4.624306,1.161459,1.434379,0.708218,0.289232,0.113178,0.011052,0.996139
128,Cambodia,129,4.168,4.278518,4.057483,0.601765,1.006238,0.429783,0.633376,0.385923,0.068106,1.042941
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
88,Portugal,89,5.195,5.285042,5.104959,1.315175,1.367043,0.795844,0.498465,0.095103,0.015869,1.107683
99,Mongolia,100,4.955,5.021680,4.888320,1.027236,1.493011,0.557783,0.394144,0.338464,0.032902,1.111292
113,Myanmar,114,4.545,4.614740,4.475260,0.367111,1.123236,0.397523,0.514492,0.838075,0.188816,1.115290
96,Bhutan,97,5.011,5.079335,4.942666,0.885416,1.340127,0.495879,0.501538,0.474055,0.173380,1.140184
34,Qatar,35,6.375,6.568477,6.181523,1.870766,1.274297,0.710098,0.604131,0.330474,0.439299,1.145464
25,Singapore,26,6.572,6.636723,6.507277,1.692278,1.353814,0.949492,0.549841,0.345966,0.464308,1.216362
61,Slovenia,62,5.758,5.842225,5.673775,1.341206,1.452519,0.790828,0.572576,0.242649,0.045129,1.313317
116,Iraq,117,4.497,4.622591,4.371409,1.102710,0.978613,0.501180,0.288556,0.199637,0.107216,1.318907
85,Dominican Republic,86,5.230,5.349061,5.110939,1.079374,1.402417,0.574874,0.552590,0.186968,0.113945,1.319465
117,Gabon,118,4.465,4.557362,4.372639,1.198210,1.155620,0.356579,0.312329,0.043785,0.076047,1.322916
145,Yemen,146,3.593,3.692750,3.493250,0.591683,0.935382,0.310081,0.249464,0.104125,0.056767,1.345601