In [1]:
# Import Dependencies
import pandas as pd

In [2]:
# Reference the file where the CSV is located
file = 'Resources/crime_incident_data2017.csv'
# Import the data into a Pandas DataFrame
df = pd.read_csv(file, encoding="ISO-8859-1")

In [4]:
df

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
0,NaN,17-X4762181,Person,NaN,1,1/1/96,1/1/96,800,Sex Offenses,1,Rape,NaN,NaN,NaN,NaN,1/26/17,1/1/17
1,NaN,17-X4757824,Property,Centennial,1,1/20/00,1/1/00,1615,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/20/17,1/1/17
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1,12/1/03,12/1/03,800,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17
3,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/5/17,1/1/17
4,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Larceny Offenses,1,All Other Larceny,NaN,NaN,NaN,NaN,1/5/17,1/1/17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41027,8800 BLOCK OF NE SANDY BLVD,17-285386,Society,Sumner,1,8/31/17,8/1/17,535,Drug/Narcotic Offenses,1,Drug/Narcotic Violations,45.5554,-122.571,7671560.0,695399.0,8/31/17,8/1/17
41028,9700 BLOCK OF SE STARK ST,17-286082,Society,Hazelwood,1,8/31/17,8/1/17,1619,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41029,9700 BLOCK OF SE STARK ST,17-286413,Society,Hazelwood,1,8/31/17,8/1/17,1959,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41030,UNKNOWN ADDRESS,17-286445,Society,NaN,1,8/31/17,8/1/17,2021,Prostitution Offenses,1,Prostitution,NaN,NaN,NaN,NaN,8/31/17,8/1/17
41031,8000 BLOCK OF SE POWELL BLVD,17-286659,Society,Foster-Powell,1,8/31/17,8/1/17,2354,Weapon Law Violations,1,Weapons Law Violations,45.4974,-122.580,7668725.0,674298.0,8/31/17,8/1/17

In [3]:
# look for missing values
df.count()

Address              37365
Case Number          41032
Crime Against        41032
Neighborhood         39712
Number of Records    41032
Occur Date           41032
Occur Month Year     41032
Occur Time           41032
Offense Category     41032
Offense Count        41032
Offense Type         41032
Open Data Lat        36712
Open Data Lon        36712
Open Data X          36712
Open Data Y          36712
Report Date          41032
Report Month Year    41032
dtype: int64

In [5]:
# drop null rows
cleaned_df = df.dropna(how='any')

In [6]:
# verify counts
cleaned_df.count()

Address              36146
Case Number          36146
Crime Against        36146
Neighborhood         36146
Number of Records    36146
Occur Date           36146
Occur Month Year     36146
Occur Time           36146
Offense Category     36146
Offense Count        36146
Offense Type         36146
Open Data Lat        36146
Open Data Lon        36146
Open Data X          36146
Open Data Y          36146
Report Date          36146
Report Month Year    36146
dtype: int64

In [12]:
# Check to see if there are any values with mispelled or similar values in "Offense Type"
cleaned_df['Offense Type'].value_counts()

Motor Vehicle Theft                           12709
Burglary                                       6769
All Other Larceny                              4558
Vandalism                                      3863
Identity Theft                                 1794
Simple Assault                                 1216
Drug/Narcotic Violations                       1095
Intimidation                                    900
False Pretenses/Swindle/Confidence Game         870
Aggravated Assault                              839
Counterfeiting/Forgery                          448
Weapons Law Violations                          266
Credit Card/ATM Fraud                           226
Arson                                           200
Prostitution                                    145
Embezzlement                                     73
Stolen Property Offenses                         57
Kidnapping/Abduction                             22
Theft From Coin-Operated Machine or Device       20
Hacking/Computer Invasion                        19
Animal Cruelty                                   17
Pornography/Obscene Material                     10
Extortion/Blackmail                               8
Assisting or Promoting Prostitution               7
Drug Equipment Violations                         6
Impersonation                                     4
Wire Fraud                                        3
Welfare Fraud                                     1
Commercial Sex Acts                               1
Name: Offense Type, dtype: int64

In [11]:
# Combine similar offenses
#Real world you would clarify what would be grouped together before grouping
cleaned_df['Offense Type'] = cleaned_df['Offense Type'].replace(
    {'Theft From Motor Vehicle': 'Motor Vehicle Theft', 'Theft of Motor Vehicle Parts or Accessories': 'Motor Vehicle Theft'})
cleaned_df['Offense Type'] = cleaned_df['Offense Type'].replace(
    {'Robbery': 'Burglary', 'Shoplifting': 'Burglary','Pocket-Picking': 'Burglary','Purse-Snatching': 'Burglary','Theft From Building': 'Burglary',})

<ipython-input-11-78260afa4ab7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df['Offense Type'] = cleaned_df['Offense Type'].replace(
<ipython-input-11-78260afa4ab7>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df['Offense Type'] = cleaned_df['Offense Type'].replace(

In [ ]:
# Check to see if you comnbined similar offenses correctly in "Offense Type".
#Just re-did step above

In [16]:
# Create a new DataFrame that looks into a specific neighborhood
Sumner_df = cleaned_df.loc[cleaned_df["Neighborhood"] == "Sumner", : ]
Sumner_df

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
330,4400 BLOCK OF NE 83RD AVE,17-900221,Property,Sumner,1,12/10/16,12/1/16,1112,Fraud Offenses,1,Identity Theft,45.5551,-122.578,7669952.0,695312.0,1/5/17,1/1/17
355,8200 BLOCK OF NE SANDY BLVD,17-900267,Property,Sumner,1,12/15/16,12/1/16,1055,Larceny Offenses,1,Motor Vehicle Theft,45.5527,-122.578,7669791.0,694433.0,1/6/17,1/1/17
469,8200 BLOCK OF NE GOING ST,17-22551,Property,Sumner,1,12/28/16,12/1/16,2131,Motor Vehicle Theft,1,Motor Vehicle Theft,45.5567,-122.578,7669863.0,695911.0,1/23/17,1/1/17
676,8200 BLOCK OF NE SANDY BLVD,17-1697,Property,Sumner,1,1/2/17,1/1/17,1844,Larceny Offenses,1,Burglary,45.5527,-122.578,7669791.0,694433.0,1/2/17,1/1/17
952,8800 BLOCK OF NE SANDY BLVD,17-900208,Property,Sumner,1,1/2/17,1/1/17,1210,Larceny Offenses,1,Motor Vehicle Theft,45.5554,-122.571,7671560.0,695399.0,1/5/17,1/1/17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40253,8900 BLOCK OF NE KILLINGSWORTH ST,17-802917,Property,Sumner,1,8/27/17,8/1/17,2116,Arson,1,Arson,45.5626,-122.571,7671813.0,698013.0,8/27/17,8/1/17
40421,8800 BLOCK OF NE SANDY BLVD,17-281677,Property,Sumner,1,8/28/17,8/1/17,745,Burglary,1,Burglary,45.5554,-122.571,7671576.0,695371.0,8/28/17,8/1/17
40575,NE 82ND AVE / NE SANDY BLVD,17-282862,Property,Sumner,1,8/28/17,8/1/17,1400,Vandalism,1,Vandalism,45.5524,-122.579,7669676.0,694352.0,8/29/17,8/1/17
40998,8400 BLOCK OF NE COLUMBIA BLVD,17-912758,Property,Sumner,1,8/31/17,8/1/17,125,Larceny Offenses,1,Motor Vehicle Theft,45.5644,-122.576,7670537.0,698691.0,8/31/17,8/1/17
41027,8800 BLOCK OF NE SANDY BLVD,17-285386,Society,Sumner,1,8/31/17,8/1/17,535,Drug/Narcotic Offenses,1,Drug/Narcotic Violations,45.5554,-122.571,7671560.0,695399.0,8/31/17,8/1/17