In [1]:
# Dependencies
import pandas as pd

In [2]:
# Save file path to variable
file = "Resources/Pokemon.csv"

In [3]:
# Read with Pandas
poke_df = pd.read_csv(file)

In [13]:
poke_df
new_df = poke_df[["Name", "Type 1", "HP", "Attack", "Sp. Atk", "Sp. Def", "Speed"]]
#This sets a new dataframe with the below extractions
poke_df

,Name,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,Bulbasaur,Grass,45,49,49,65,65,45
1,Ivysaur,Grass,60,62,63,80,80,60
2,Venusaur,Grass,80,82,83,100,100,80
3,VenusaurMega Venusaur,Grass,80,100,123,122,120,80
4,Charmander,Fire,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...
795,Diancie,Rock,50,100,150,100,150,50
796,DiancieMega Diancie,Rock,50,160,110,160,110,110
797,HoopaHoopa Confined,Psychic,80,110,60,150,130,70
798,HoopaHoopa Unbound,Psychic,80,160,60,170,130,80
799,Volcanion,Fire,80,110,120,130,90,70

In [19]:
# Extract the following columns: "Type 1", "HP", "Attack", "Sp. Atk", "Sp. Def", and "Speed"
#Another way to create the new dataframe by modifying existing
del poke_df["Type 2"]
del poke_df["Generation"]
del poke_df["#"]
del poke_df["Legendary"]
del poke_df["Total"]
poke_df.head(3)

KeyError: 'Type 2'

In [18]:
new_df.head(3)

        Name Type 1  HP  Attack  Sp. Atk  Sp. Def  Speed
0  Bulbasaur  Grass  45      49       65       65     45
1    Ivysaur  Grass  60      62       80       80     60
2   Venusaur  Grass  80      82      100      100     80

In [20]:
# Create a dataframe of the average stats for each type of pokemon.
poke_group = new_df.groupby(["Type 1"])

poke_stats_df = poke_group.mean()
poke_stats_df

                 HP      Attack    Sp. Atk    Sp. Def       Speed
Type 1
Bug       56.884058   70.971014  53.869565  64.797101   61.681159
Dark      66.806452   88.387097  74.645161  69.516129   76.161290
Dragon    83.312500  112.125000  96.843750  88.843750   83.031250
Electric  59.795455   69.090909  90.022727  73.704545   84.500000
Fairy     74.117647   61.529412  78.529412  84.705882   48.588235
Fighting  69.851852   96.777778  53.111111  64.703704   66.074074
Fire      69.903846   84.769231  88.980769  72.211538   74.442308
Flying    70.750000   78.750000  94.250000  72.500000  102.500000
Ghost     64.437500   73.781250  79.343750  76.468750   64.343750
Grass     67.271429   73.214286  77.500000  70.428571   61.928571
Ground    73.781250   95.750000  56.468750  62.750000   63.906250
Ice       72.000000   72.750000  77.541667  76.291667   63.458333
Normal    77.275510   73.469388  55.816327  63.724490   71.551020
Poison    67.250000   74.678571  60.428571  64.392857   63.571429
Psychic   70.631579   71.456140  98.403509  86.280702   81.491228
Rock      65.363636   92.863636  63.340909  75.477273   55.909091
Steel     65.222222   92.703704  67.518519  80.629630   55.259259
Water     72.062500   74.151786  74.812500  70.517857   65.964286

In [23]:
# Calculate the total power level of each type of pokemon by summing all of the stats together.
# Place the results into a new column.
# Hint: Research the sum method from pandas.
poke_stats_df["Total Power"] = poke_stats_df.sum(axis=1)
#(axis=1) switches the sum from columns to rows
poke_stats_df

                 HP      Attack    Sp. Atk    Sp. Def       Speed  Total Power
Type 1
Bug       56.884058   70.971014  53.869565  64.797101   61.681159   616.405797
Dark      66.806452   88.387097  74.645161  69.516129   76.161290   751.032258
Dragon    83.312500  112.125000  96.843750  88.843750   83.031250   928.312500
Electric  59.795455   69.090909  90.022727  73.704545   84.500000   754.227273
Fairy     74.117647   61.529412  78.529412  84.705882   48.588235   694.941176
Fighting  69.851852   96.777778  53.111111  64.703704   66.074074   701.037037
Fire      69.903846   84.769231  88.980769  72.211538   74.442308   780.615385
Flying    70.750000   78.750000  94.250000  72.500000  102.500000   837.500000
Ghost     64.437500   73.781250  79.343750  76.468750   64.343750   716.750000
Grass     67.271429   73.214286  77.500000  70.428571   61.928571   700.685714
Ground    73.781250   95.750000  56.468750  62.750000   63.906250   705.312500
Ice       72.000000   72.750000  77.541667  76.291667   63.458333   724.083333
Normal    77.275510   73.469388  55.816327  63.724490   71.551020   683.673469
Poison    67.250000   74.678571  60.428571  64.392857   63.571429   660.642857
Psychic   70.631579   71.456140  98.403509  86.280702   81.491228   816.526316
Rock      65.363636   92.863636  63.340909  75.477273   55.909091   705.909091
Steel     65.222222   92.703704  67.518519  80.629630   55.259259   722.666667
Water     72.062500   74.151786  74.812500  70.517857   65.964286   715.017857

In [26]:
# Bonus: Sort the table by strongest type and export the resulting table to a new CSV.
sorted_df = poke_stats_df.sort_values("Total Power",ascending=False)
#ascending=False puts strongest at the top
sorted_df

                 HP      Attack    Sp. Atk    Sp. Def       Speed  Total Power
Type 1
Dragon    83.312500  112.125000  96.843750  88.843750   83.031250   928.312500
Flying    70.750000   78.750000  94.250000  72.500000  102.500000   837.500000
Psychic   70.631579   71.456140  98.403509  86.280702   81.491228   816.526316
Fire      69.903846   84.769231  88.980769  72.211538   74.442308   780.615385
Electric  59.795455   69.090909  90.022727  73.704545   84.500000   754.227273
Dark      66.806452   88.387097  74.645161  69.516129   76.161290   751.032258
Ice       72.000000   72.750000  77.541667  76.291667   63.458333   724.083333
Steel     65.222222   92.703704  67.518519  80.629630   55.259259   722.666667
Ghost     64.437500   73.781250  79.343750  76.468750   64.343750   716.750000
Water     72.062500   74.151786  74.812500  70.517857   65.964286   715.017857
Rock      65.363636   92.863636  63.340909  75.477273   55.909091   705.909091
Ground    73.781250   95.750000  56.468750  62.750000   63.906250   705.312500
Fighting  69.851852   96.777778  53.111111  64.703704   66.074074   701.037037
Grass     67.271429   73.214286  77.500000  70.428571   61.928571   700.685714
Fairy     74.117647   61.529412  78.529412  84.705882   48.588235   694.941176
Normal    77.275510   73.469388  55.816327  63.724490   71.551020   683.673469
Poison    67.250000   74.678571  60.428571  64.392857   63.571429   660.642857
Bug       56.884058   70.971014  53.869565  64.797101   61.681159   616.405797

In [27]:
sorted_df.to_csv("poke.csv")