In [ ]:
#Scroll to bottom for Key Stats**

In [3]:
#Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np
from scipy.stats import linregress

file = "GamingStudy_dataKaggle.csv"

dataset = pd.read_csv(file, encoding="ISO-8859-1")

In [4]:
dataset.head()

,S. No.,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GADE,...,Birthplace,Residence,Reference,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,...,USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,...,USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,...,Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU
3,4,42052.06804,0,0,0,0,0,0,0,Not difficult at all,...,USA,USA,Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11.0,USA,USA
4,5,42052.08948,2,1,2,2,2,3,2,Very difficult,...,USA,South Korea,Reddit,Multiplayer - online - with strangers,Accept,14,14,13.0,KOR,USA

In [16]:
earnings_df = dataset[["S. No.", "Platform", "Hours", "earnings", "Gender", "Age", "Work",
"Degree", "Birthplace", "Residence", "Playstyle","Narcissism", "GAD_T", "SWL_T", "SPIN_T"]]
earnings_df

,S. No.,Platform,Hours,earnings,Gender,Age,Work,Degree,Birthplace,Residence,Playstyle,Narcissism,GAD_T,SWL_T,SPIN_T
0,1,"Console (PS, Xbox, ...)",15.0,I play for fun,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Singleplayer,1.0,1,23,5.0
1,2,PC,8.0,I play for fun,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Multiplayer - online - with strangers,1.0,8,16,33.0
2,3,PC,0.0,I play for fun,Female,32,Employed,Bachelor (or equivalent),Germany,Germany,Singleplayer,4.0,8,17,31.0
3,4,PC,20.0,I play for fun,Male,28,Employed,Bachelor (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,2.0,0,17,11.0
4,5,"Console (PS, Xbox, ...)",20.0,I play for fun,Male,19,Employed,High school diploma (or equivalent),USA,South Korea,Multiplayer - online - with strangers,1.0,14,14,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13459,14246,"Console (PS, Xbox, ...)",40.0,I play for fun,Male,22,Student at college / university,Master (or equivalent),France,France,Multiplayer - online - with strangers,3.0,4,28,7.0
13460,14247,PC,20.0,I play for fun,Female,20,Student at college / university,High school diploma (or equivalent),USA,USA,Multiplayer - online - with strangers,2.0,20,23,25.0
13461,14248,PC,20.0,I play for fun,Male,19,Student at college / university,High school diploma (or equivalent),Norway,Norway,Multiplayer - online - with real life friends,2.0,0,32,10.0
13462,14249,"Console (PS, Xbox, ...)",5.0,I play for fun,Female,18,Student at school,High school diploma (or equivalent),Canada,Canada,Singleplayer,2.0,13,16,32.0
13463,14250,PC,15.0,I play for fun,Male,19,Student at college / university,High school diploma (or equivalent),Canada,Canada,Multiplayer - online - with strangers,2.0,2,25,14.0

In [68]:
earnings_df['Residence'].value_counts().nlargest(10)

USA            4569
Germany        1413
UK             1032
Canada          994
Netherlands     506
France          391
Sweden          379
Denmark         254
Brazil          253
Australia       245
Name: Residence, dtype: int64

In [17]:
loc_df = earnings_df.loc[earnings_df['Residence'] == "USA", :]
loc_df

,S. No.,Platform,Hours,earnings,Gender,Age,Work,Degree,Birthplace,Residence,Playstyle,Narcissism,GAD_T,SWL_T,SPIN_T
0,1,"Console (PS, Xbox, ...)",15.0,I play for fun,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Singleplayer,1.0,1,23,5.0
1,2,PC,8.0,I play for fun,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Multiplayer - online - with strangers,1.0,8,16,33.0
3,4,PC,20.0,I play for fun,Male,28,Employed,Bachelor (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,2.0,0,17,11.0
5,6,"Console (PS, Xbox, ...)",4.0,I play for fun,Male,24,Employed,Bachelor (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,1,17,13.0
6,7,PC,30.0,I play for fun,Male,29,Employed,High school diploma (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,2.0,0,16,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13451,14237,PC,20.0,I play for fun,Male,18,Student at college / university,High school diploma (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,2,27,33.0
13452,14238,PC,10.0,I play for fun,Male,27,Student at college / university,Bachelor (or equivalent),USA,USA,Multiplayer - online - with real life friends,1.0,2,17,23.0
13454,14240,"Console (PS, Xbox, ...)",40.0,I play for fun,Male,24,Employed,High school diploma (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,6,12,NaN
13458,14245,PC,30.0,I play for fun,Male,21,Unemployed / between jobs,High school diploma (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,2.0,6,16,12.0
13460,14247,PC,20.0,I play for fun,Female,20,Student at college / university,High school diploma (or equivalent),USA,USA,Multiplayer - online - with strangers,2.0,20,23,25.0

In [18]:
forFun_df = loc_df.loc[loc_df['earnings'] == "I play for fun", :]
forFun_df

,S. No.,Platform,Hours,earnings,Gender,Age,Work,Degree,Birthplace,Residence,Playstyle,Narcissism,GAD_T,SWL_T,SPIN_T
0,1,"Console (PS, Xbox, ...)",15.0,I play for fun,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Singleplayer,1.0,1,23,5.0
1,2,PC,8.0,I play for fun,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Multiplayer - online - with strangers,1.0,8,16,33.0
3,4,PC,20.0,I play for fun,Male,28,Employed,Bachelor (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,2.0,0,17,11.0
5,6,"Console (PS, Xbox, ...)",4.0,I play for fun,Male,24,Employed,Bachelor (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,1,17,13.0
6,7,PC,30.0,I play for fun,Male,29,Employed,High school diploma (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,2.0,0,16,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13451,14237,PC,20.0,I play for fun,Male,18,Student at college / university,High school diploma (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,2,27,33.0
13452,14238,PC,10.0,I play for fun,Male,27,Student at college / university,Bachelor (or equivalent),USA,USA,Multiplayer - online - with real life friends,1.0,2,17,23.0
13454,14240,"Console (PS, Xbox, ...)",40.0,I play for fun,Male,24,Employed,High school diploma (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,6,12,NaN
13458,14245,PC,30.0,I play for fun,Male,21,Unemployed / between jobs,High school diploma (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,2.0,6,16,12.0
13460,14247,PC,20.0,I play for fun,Female,20,Student at college / university,High school diploma (or equivalent),USA,USA,Multiplayer - online - with strangers,2.0,20,23,25.0

In [20]:
funUnemp_df = forFun_df.loc[forFun_df['Work'] == "Unemployed / between jobs", :]
funUnemp_df

,S. No.,Platform,Hours,earnings,Gender,Age,Work,Degree,Birthplace,Residence,Playstyle,Narcissism,GAD_T,SWL_T,SPIN_T
0,1,"Console (PS, Xbox, ...)",15.0,I play for fun,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Singleplayer,1.0,1,23,5.0
1,2,PC,8.0,I play for fun,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Multiplayer - online - with strangers,1.0,8,16,33.0
18,19,PC,10.0,I play for fun,Male,29,Unemployed / between jobs,High school diploma (or equivalent),Germany,USA,Singleplayer,1.0,8,6,36.0
80,83,"Console (PS, Xbox, ...)",25.0,I play for fun,Female,34,Unemployed / between jobs,Master (or equivalent),USA,USA,Singleplayer,1.0,10,22,38.0
100,104,PC,15.0,I play for fun,Male,20,Unemployed / between jobs,High school diploma (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,0,18,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13228,14001,PC,20.0,I play for fun,Male,22,Unemployed / between jobs,High school diploma (or equivalent),USA,USA,Multiplayer - online - with real life friends,1.0,3,6,46.0
13237,14010,PC,20.0,I play for fun,Male,18,Unemployed / between jobs,High school diploma (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,1.0,15,10,30.0
13271,14048,PC,14.0,I play for fun,Male,18,Unemployed / between jobs,High school diploma (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,8,16,0.0
13436,14222,PC,15.0,I play for fun,Female,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Multiplayer - online - with strangers,1.0,2,28,15.0
13458,14245,PC,30.0,I play for fun,Male,21,Unemployed / between jobs,High school diploma (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,2.0,6,16,12.0

In [43]:
funUni_df = forFun_df.loc[forFun_df['Work'] == "Student at college / university", :]
# funSchool_df = forFun_df.loc[forFun_df['Work'] == "Student at school", :]
funUni_df

,S. No.,Platform,Hours,earnings,Gender,Age,Work,Degree,Birthplace,Residence,Playstyle,Narcissism,GAD_T,SWL_T,SPIN_T
10,11,PC,14.0,I play for fun,Female,21,Student at college / university,High school diploma (or equivalent),USA,USA,Singleplayer,1.0,19,27,6.0
12,13,PC,10.0,I play for fun,Male,18,Student at college / university,High school diploma (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,0,31,23.0
28,29,"Console (PS, Xbox, ...)",40.0,I play for fun,Male,19,Student at college / university,High school diploma (or equivalent),USA,USA,Multiplayer - online - with real life friends,1.0,4,24,15.0
35,36,PC,7.0,I play for fun,Male,25,Student at college / university,Master (or equivalent),USA,USA,Multiplayer - online - with strangers,2.0,1,21,29.0
37,38,"Console (PS, Xbox, ...)",18.0,I play for fun,Male,24,Student at college / university,High school diploma (or equivalent),USA,USA,Singleplayer,3.0,14,13,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13441,14227,PC,20.0,I play for fun,Male,22,Student at college / university,High school diploma (or equivalent),USA,USA,Multiplayer - online - with strangers,1.0,1,17,3.0
13444,14230,PC,40.0,I play for fun,Male,21,Student at college / university,Bachelor (or equivalent),Pakistan,USA,Multiplayer - online - with real life friends,1.0,1,22,22.0
13451,14237,PC,20.0,I play for fun,Male,18,Student at college / university,High school diploma (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,2,27,33.0
13452,14238,PC,10.0,I play for fun,Male,27,Student at college / university,Bachelor (or equivalent),USA,USA,Multiplayer - online - with real life friends,1.0,2,17,23.0
13460,14247,PC,20.0,I play for fun,Female,20,Student at college / university,High school diploma (or equivalent),USA,USA,Multiplayer - online - with strangers,2.0,20,23,25.0

In [22]:
funEmp_df = forFun_df.loc[forFun_df['Work'] == "Employed", :]
funEmp_df

,S. No.,Platform,Hours,earnings,Gender,Age,Work,Degree,Birthplace,Residence,Playstyle,Narcissism,GAD_T,SWL_T,SPIN_T
3,4,PC,20.0,I play for fun,Male,28,Employed,Bachelor (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,2.0,0,17,11.0
5,6,"Console (PS, Xbox, ...)",4.0,I play for fun,Male,24,Employed,Bachelor (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,1,17,13.0
6,7,PC,30.0,I play for fun,Male,29,Employed,High school diploma (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,2.0,0,16,26.0
8,9,"Console (PS, Xbox, ...)",2.0,I play for fun,Female,23,Employed,Bachelor (or equivalent),USA,USA,Multiplayer - online - with strangers,1.0,12,12,55.0
11,12,PC,25.0,I play for fun,Male,25,Employed,Bachelor (or equivalent),USA,USA,Multiplayer - online - with real life friends,1.0,0,33,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13411,14197,PC,25.0,I play for fun,Male,24,Employed,Bachelor (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,3,30,23.0
13413,14199,PC,5.0,I play for fun,Male,30,Employed,High school diploma (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,2.0,2,25,16.0
13427,14213,PC,20.0,I play for fun,Male,32,Employed,Master (or equivalent),UK,USA,Multiplayer - online - with online acquaintanc...,1.0,3,34,8.0
13440,14226,PC,45.0,I play for fun,Male,19,Employed,High school diploma (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...,5.0,2,35,7.0
13454,14240,"Console (PS, Xbox, ...)",40.0,I play for fun,Male,24,Employed,High school diploma (or equivalent),USA,USA,Multiplayer - online - with real life friends,2.0,6,12,NaN

In [ ]:
#GAD_T - score of 10 or greater, further eval is recommended
#  .loc[_df['GAD_T'] > 9]
#SWL_T - under 20 is dissatisfied
#  _df.loc[_df['SWL_T'] < 20]
#SPIN_T - score of 20 or greater suggests a diagnosis of social anxiety disorder
#  _df.loc[_df['SPIN_T'] > 19]

In [86]:
#Total Counts for US-Based Gamers who play for fun
funT_Count = len(forFun_df['S. No.'])

maleT = forFun_df.loc[forFun_df['Gender'] == "Male"]
femaleT = forFun_df.loc[forFun_df['Gender'] == "Female"]
otherT = forFun_df.loc[forFun_df['Gender'] == "Other"]

funM_Count = len(maleT['S. No.'])
funF_Count = len(femaleT['S. No.'])
funO_Count = len(otherT['S. No.'])

# print(f"Surveyed US-Based Gamers who play for fun: {funT_Count}")
# print(f"Male: {funM_Count}")   
# print(f"Female: {funF_Count}")  
# print(f"Other: {funO_Count}")

In [87]:
#Baseline Scores for US-Based Gamers who play for fun
GAD_df = forFun_df.loc[forFun_df['GAD_T'] > 9]
SWL_df = forFun_df.loc[forFun_df['SWL_T'] < 20]
SPIN_df = forFun_df.loc[forFun_df['SPIN_T'] > 19]

GAD_Count = len(GAD_df['S. No.'])
G_Percent = round(GAD_Count / funT_Count * 100,2)
SWL_Count = len(SWL_df['S. No.'])
SW_Percent = round(SWL_Count / funT_Count * 100,2)
SPIN_Count = len(SPIN_df['S. No.'])
SP_Percent = round(SPIN_Count / funT_Count * 100,2)

# print(f"Total GAD Count: {GAD_Count}  /  {G_Percent}%")
# print(f"Total SWL Count: {SWL_Count}  /  {SW_Percent}%")
# print(f"Total SPIN Count: {SPIN_Count}  /  {SP_Percent}%")

In [88]:
#Unemployed
Un_GAD_df = funUnemp_df.loc[funUnemp_df['GAD_T'] > 9]
Un_SWL_df = funUnemp_df.loc[funUnemp_df['SWL_T'] < 20]
Un_SPIN_df = funUnemp_df.loc[funUnemp_df['SPIN_T'] > 19]
UnMale = funUnemp_df.loc[funUnemp_df['Gender'] == "Male"]
UnFemale = funUnemp_df.loc[funUnemp_df['Gender'] == "Female"]
UnOther = funUnemp_df.loc[funUnemp_df['Gender'] == "Other"]

Un_Count = len(funUnemp_df['S. No.'])
UnM_Count = len(UnMale['S. No.'])
UnF_Count = len(UnFemale['S. No.'])
UnO_Count = len(UnOther['S. No.'])
Un_GAD_Count = len(Un_GAD_df['S. No.'])
UnG_Percent = round(Un_GAD_Count / Un_Count * 100,2)
Un_SWL_Count = len(Un_SWL_df['S. No.'])
UnSW_Percent = round(Un_SWL_Count / Un_Count * 100,2)
Un_SPIN_Count = len(Un_SPIN_df['S. No.'])
UnSP_Percent = round(Un_SPIN_Count / Un_Count * 100,2)

# print(f"Total Unemployed: {Un_Count}")
# print(f"Total Male Unemployed: {UnM_Count}")
# print(f"Total Female Unemployed: {UnF_Count}")
# print(f"Total Other Unemployed: {UnO_Count}")
# print(f"Total Unemployed GAD Count: {Un_GAD_Count}  /  {UnG_Percent}%")
# print(f"Total Unemployed SWL Count: {Un_SWL_Count}  /  {UnSW_Percent}%")
# print(f"Total Unemployed SPIN Count: {Un_SPIN_Count}  /  {UnSP_Percent}%")

In [89]:
#Employed
Em_GAD_df = funEmp_df.loc[funEmp_df['GAD_T'] > 9]
Em_SWL_df = funEmp_df.loc[funEmp_df['SWL_T'] < 20]
Em_SPIN_df = funEmp_df.loc[funEmp_df['SPIN_T'] > 19]
EmMale = funEmp_df.loc[funEmp_df['Gender'] == "Male"]
EmFemale = funEmp_df.loc[funEmp_df['Gender'] == "Female"]
EmOther = funEmp_df.loc[funEmp_df['Gender'] == "Other"]

Em_Count = len(funEmp_df['S. No.'])
EmM_Count = len(EmMale['S. No.'])
EmF_Count = len(EmFemale['S. No.'])
EmO_Count = len(EmOther['S. No.'])
Em_GAD_Count = len(Em_GAD_df['S. No.'])
EmG_Percent = round(Em_GAD_Count / Em_Count * 100,2)
Em_SWL_Count = len(Em_SWL_df['S. No.'])
EmSW_Percent = round(Em_SWL_Count / Em_Count * 100,2)
Em_SPIN_Count = len(Em_SPIN_df['S. No.'])
EmSP_Percent = round(Em_SPIN_Count / Em_Count * 100,2)

# print(f"Total Employed: {Em_Count}")
# print(f"Total Male Employed: {EmM_Count}")
# print(f"Total Female Employed: {EmF_Count}")
# print(f"Total Other Employed: {EmO_Count}")
# print(f"Total Employed GAD Count: {Em_GAD_Count}  /  {EmG_Percent}%")
# print(f"Total Employed SWL Count: {Em_SWL_Count}  /  {EmSW_Percent}%")
# print(f"Total Employed SPIN Count: {Em_SPIN_Count}  /  {EmSP_Percent}%")

In [90]:
#Uni Student
St_GAD_df = funUni_df.loc[funUni_df['GAD_T'] > 9]
St_SWL_df = funUni_df.loc[funUni_df['SWL_T'] < 20]
St_SPIN_df = funUni_df.loc[funUni_df['SPIN_T'] > 19]
StMale = funUni_df.loc[funUni_df['Gender'] == "Male"]
StFemale = funUni_df.loc[funUni_df['Gender'] == "Female"]
StOther = funUni_df.loc[funUni_df['Gender'] == "Other"]

St_Count = len(funUni_df['S. No.'])
StM_Count = len(StMale['S. No.'])
StF_Count = len(StFemale['S. No.'])
StO_Count = len(StOther['S. No.'])
St_GAD_Count = len(St_GAD_df['S. No.'])
StG_Percent = round(St_GAD_Count / St_Count * 100,2)
St_SWL_Count = len(St_SWL_df['S. No.'])
StSW_Percent = round(St_SWL_Count / St_Count * 100,2)
St_SPIN_Count = len(St_SPIN_df['S. No.'])
StSP_Percent = round(St_SPIN_Count / St_Count * 100,2)

# print(f"Total Uni Student: {St_Count}")
# print(f"Total Male Employed: {StM_Count}")
# print(f"Total Female Employed: {StF_Count}")
# print(f"Total Other Employed: {StO_Count}")
# print(f"Total Uni Student GAD Count: {St_GAD_Count}  /  {StG_Percent}%")
# print(f"Total Uni Student SWL Count: {St_SWL_Count}  /  {StSW_Percent}%")
# print(f"Total Uni Student SPIN Count: {St_SPIN_Count}  /  {StSP_Percent}%")

In [111]:
#Germany df
Gerloc_df = earnings_df.loc[earnings_df['Residence'] == "Germany", :]
GerforFun_df = Gerloc_df.loc[Gerloc_df['earnings'] == "I play for fun", :]
GerfunUnemp_df = GerforFun_df.loc[GerforFun_df['Work'] == "Unemployed / between jobs", :]
GerfunUni_df = GerforFun_df.loc[GerforFun_df['Work'] == "Student at college / university", :]
GerfunEmp_df = GerforFun_df.loc[GerforFun_df['Work'] == "Employed", :]

In [112]:
#Total Counts for Germany-Based Gamers who play for fun
GerfunT_Count = len(GerforFun_df['S. No.'])

GermaleT = GerforFun_df.loc[GerforFun_df['Gender'] == "Male"]
GerfemaleT = GerforFun_df.loc[GerforFun_df['Gender'] == "Female"]
GerotherT = GerforFun_df.loc[GerforFun_df['Gender'] == "Other"]

GerfunM_Count = len(GermaleT['S. No.'])
GerfunF_Count = len(GerfemaleT['S. No.'])
GerfunO_Count = len(GerotherT['S. No.'])

#Baseline Scores for US-Based Gamers who play for fun
GerGAD_df = GerforFun_df.loc[GerforFun_df['GAD_T'] > 9]
GerSWL_df = GerforFun_df.loc[GerforFun_df['SWL_T'] < 20]
GerSPIN_df = GerforFun_df.loc[GerforFun_df['SPIN_T'] > 19]

GerGAD_Count = len(GerGAD_df['S. No.'])
GerG_Percent = round(GerGAD_Count / GerfunT_Count * 100,2)
GerSWL_Count = len(GerSWL_df['S. No.'])
GerSW_Percent = round(GerSWL_Count / GerfunT_Count * 100,2)
GerSPIN_Count = len(GerSPIN_df['S. No.'])
GerSP_Percent = round(GerSPIN_Count / GerfunT_Count * 100,2)

# print(f"Total GAD Count: {GerGAD_Count}  /  {GerG_Percent}%")
# print(f"Total SWL Count: {GerSWL_Count}  /  {GerSW_Percent}%")
# print(f"Total SPIN Count: {GerSPIN_Count}  /  {GerSP_Percent}%")
# print(f"Surveyed Germany-Based Gamers who play for fun: {GerfunT_Count}")
# print(f"Male: {GerfunM_Count}")   
# print(f"Female: {GerfunF_Count}")  
# print(f"Other: {GerfunO_Count}")

In [113]:
#Unemployed
GerUn_GAD_df = GerfunUnemp_df.loc[GerfunUnemp_df['GAD_T'] > 9]
GerUn_SWL_df = GerfunUnemp_df.loc[GerfunUnemp_df['SWL_T'] < 20]
GerUn_SPIN_df = GerfunUnemp_df.loc[GerfunUnemp_df['SPIN_T'] > 19]
GerUnMale = GerfunUnemp_df.loc[GerfunUnemp_df['Gender'] == "Male"]
GerUnFemale = GerfunUnemp_df.loc[GerfunUnemp_df['Gender'] == "Female"]
GerUnOther = GerfunUnemp_df.loc[GerfunUnemp_df['Gender'] == "Other"]

GerUn_Count = len(GerfunUnemp_df['S. No.'])
GerUnM_Count = len(GerUnMale['S. No.'])
GerUnF_Count = len(GerUnFemale['S. No.'])
GerUnO_Count = len(GerUnOther['S. No.'])
GerUn_GAD_Count = len(GerUn_GAD_df['S. No.'])
GerUnG_Percent = round(GerUn_GAD_Count / GerUn_Count * 100,2)
GerUn_SWL_Count = len(GerUn_SWL_df['S. No.'])
GerUnSW_Percent = round(GerUn_SWL_Count / GerUn_Count * 100,2)
GerUn_SPIN_Count = len(GerUn_SPIN_df['S. No.'])
GerUnSP_Percent = round(GerUn_SPIN_Count / GerUn_Count * 100,2)

print(f"Total Unemployed: {GerUn_Count}")
print(f"Total Male Unemployed: {GerUnM_Count}")
print(f"Total Female Unemployed: {GerUnF_Count}")
print(f"Total Other Unemployed: {GerUnO_Count}")
print(f"Total Unemployed GAD Count: {GerUn_GAD_Count}  /  {GerUnG_Percent}%")
print(f"Total Unemployed SWL Count: {GerUn_SWL_Count}  /  {GerUnSW_Percent}%")
print(f"Total Unemployed SPIN Count: {GerUn_SPIN_Count}  /  {GerUnSP_Percent}%")

Total Unemployed: 100
Total Male Unemployed: 93
Total Female Unemployed: 7
Total Other Unemployed: 0
Total Unemployed GAD Count: 20  /  20.0%
Total Unemployed SWL Count: 81  /  81.0%
Total Unemployed SPIN Count: 47  /  47.0%

In [114]:
#Employed
GerEm_GAD_df = GerfunEmp_df.loc[GerfunEmp_df['GAD_T'] > 9]
GerEm_SWL_df = GerfunEmp_df.loc[GerfunEmp_df['SWL_T'] < 20]
GerEm_SPIN_df = GerfunEmp_df.loc[GerfunEmp_df['SPIN_T'] > 19]
GerEmMale = GerfunEmp_df.loc[GerfunEmp_df['Gender'] == "Male"]
GerEmFemale = GerfunEmp_df.loc[GerfunEmp_df['Gender'] == "Female"]
GerEmOther = GerfunEmp_df.loc[GerfunEmp_df['Gender'] == "Other"]

GerEm_Count = len(GerfunEmp_df['S. No.'])
GerEmM_Count = len(GerEmMale['S. No.'])
GerEmF_Count = len(GerEmFemale['S. No.'])
GerEmO_Count = len(GerEmOther['S. No.'])
GerEm_GAD_Count = len(GerEm_GAD_df['S. No.'])
GerEmG_Percent = round(GerEm_GAD_Count / GerEm_Count * 100,2)
GerEm_SWL_Count = len(GerEm_SWL_df['S. No.'])
GerEmSW_Percent = round(GerEm_SWL_Count / GerEm_Count * 100,2)
GerEm_SPIN_Count = len(GerEm_SPIN_df['S. No.'])
GerEmSP_Percent = round(GerEm_SPIN_Count / GerEm_Count * 100,2)

print(f"Total Employed: {GerEm_Count}")
print(f"Total Male Employed: {GerEmM_Count}")
print(f"Total Female Employed: {GerEmF_Count}")
print(f"Total Other Employed: {GerEmO_Count}")
print(f"Total Employed GAD Count: {GerEm_GAD_Count}  /  {GerEmG_Percent}%")
print(f"Total Employed SWL Count: {GerEm_SWL_Count}  /  {GerEmSW_Percent}%")
print(f"Total Employed SPIN Count: {GerEm_SPIN_Count}  /  {GerEmSP_Percent}%")

Total Employed: 216
Total Male Employed: 208
Total Female Employed: 8
Total Other Employed: 0
Total Employed GAD Count: 24  /  11.11%
Total Employed SWL Count: 90  /  41.67%
Total Employed SPIN Count: 68  /  31.48%

In [115]:
#Uni Student
GerSt_GAD_df = GerfunUni_df.loc[GerfunUni_df['GAD_T'] > 9]
GerSt_SWL_df = GerfunUni_df.loc[GerfunUni_df['SWL_T'] < 20]
GerSt_SPIN_df = GerfunUni_df.loc[GerfunUni_df['SPIN_T'] > 19]
GerStMale = GerfunUni_df.loc[GerfunUni_df['Gender'] == "Male"]
GerStFemale = GerfunUni_df.loc[GerfunUni_df['Gender'] == "Female"]
GerStOther = GerfunUni_df.loc[GerfunUni_df['Gender'] == "Other"]

GerSt_Count = len(GerfunUni_df['S. No.'])
GerStM_Count = len(GerStMale['S. No.'])
GerStF_Count = len(GerStFemale['S. No.'])
GerStO_Count = len(GerStOther['S. No.'])
GerSt_GAD_Count = len(GerSt_GAD_df['S. No.'])
GerStG_Percent = round(GerSt_GAD_Count / GerSt_Count * 100,2)
GerSt_SWL_Count = len(GerSt_SWL_df['S. No.'])
GerStSW_Percent = round(GerSt_SWL_Count / GerSt_Count * 100,2)
GerSt_SPIN_Count = len(GerSt_SPIN_df['S. No.'])
GerStSP_Percent = round(GerSt_SPIN_Count / GerSt_Count * 100,2)

print(f"Total Uni Student: {GerSt_Count}")
print(f"Total Male Employed: {GerStM_Count}")
print(f"Total Female Employed: {GerStF_Count}")
print(f"Total Other Employed: {GerStO_Count}")
print(f"Total Uni Student GAD Count: {GerSt_GAD_Count}  /  {GerStG_Percent}%")
print(f"Total Uni Student SWL Count: {GerSt_SWL_Count}  /  {GerStSW_Percent}%")
print(f"Total Uni Student SPIN Count: {GerSt_SPIN_Count}  /  {GerStSP_Percent}%")

Total Uni Student: 673
Total Male Employed: 648
Total Female Employed: 24
Total Other Employed: 1
Total Uni Student GAD Count: 74  /  11.0%
Total Uni Student SWL Count: 284  /  42.2%
Total Uni Student SPIN Count: 248  /  36.85%

In [105]:
#UK df
UKloc_df = earnings_df.loc[earnings_df['Residence'] == "UK", :]
UKforFun_df = UKloc_df.loc[UKloc_df['earnings'] == "I play for fun", :]
UKfunUnemp_df = UKforFun_df.loc[UKforFun_df['Work'] == "Unemployed / between jobs", :]
UKfunUni_df = UKforFun_df.loc[UKforFun_df['Work'] == "Student at college / university", :]
UKfunEmp_df = UKforFun_df.loc[UKforFun_df['Work'] == "Employed", :]

In [107]:
#Total Counts for UK-Based Gamers who play for fun
UKfunT_Count = len(UKforFun_df['S. No.'])

UKmaleT = UKforFun_df.loc[UKforFun_df['Gender'] == "Male"]
UKfemaleT = UKforFun_df.loc[UKforFun_df['Gender'] == "Female"]
UKotherT = UKforFun_df.loc[UKforFun_df['Gender'] == "Other"]

UKfunM_Count = len(UKmaleT['S. No.'])
UKfunF_Count = len(UKfemaleT['S. No.'])
UKfunO_Count = len(UKotherT['S. No.'])

#Baseline Scores for US-Based Gamers who play for fun
UKGAD_df = UKforFun_df.loc[UKforFun_df['GAD_T'] > 9]
UKSWL_df = UKforFun_df.loc[UKforFun_df['SWL_T'] < 20]
UKSPIN_df = UKforFun_df.loc[UKforFun_df['SPIN_T'] > 19]

UKGAD_Count = len(UKGAD_df['S. No.'])
UKG_Percent = round(UKGAD_Count / UKfunT_Count * 100,2)
UKSWL_Count = len(UKSWL_df['S. No.'])
UKSW_Percent = round(UKSWL_Count / UKfunT_Count * 100,2)
UKSPIN_Count = len(UKSPIN_df['S. No.'])
UKSP_Percent = round(UKSPIN_Count / UKfunT_Count * 100,2)

# print(f"Total GAD Count: {UKGAD_Count}  /  {UKG_Percent}%")
# print(f"Total SWL Count: {UKSWL_Count}  /  {UKSW_Percent}%")
# print(f"Total SPIN Count: {UKSPIN_Count}  /  {UKSP_Percent}%")
# print(f"Surveyed Germany-Based Gamers who play for fun: {UKfunT_Count}")
# print(f"Male: {UKfunM_Count}")   
# print(f"Female: {UKfunF_Count}")  
# print(f"Other: {UKfunO_Count}")

In [108]:
#Unemployed
UKUn_GAD_df = UKfunUnemp_df.loc[UKfunUnemp_df['GAD_T'] > 9]
UKUn_SWL_df = UKfunUnemp_df.loc[UKfunUnemp_df['SWL_T'] < 20]
UKUn_SPIN_df = UKfunUnemp_df.loc[UKfunUnemp_df['SPIN_T'] > 19]
UKUnMale = UKfunUnemp_df.loc[UKfunUnemp_df['Gender'] == "Male"]
UKUnFemale = UKfunUnemp_df.loc[UKfunUnemp_df['Gender'] == "Female"]
UKUnOther = UKfunUnemp_df.loc[UKfunUnemp_df['Gender'] == "Other"]

UKUn_Count = len(UKfunUnemp_df['S. No.'])
UKUnM_Count = len(UKUnMale['S. No.'])
UKUnF_Count = len(UKUnFemale['S. No.'])
UKUnO_Count = len(UKUnOther['S. No.'])
UKUn_GAD_Count = len(UKUn_GAD_df['S. No.'])
UKUnG_Percent = round(UKUn_GAD_Count / UKUn_Count * 100,2)
UKUn_SWL_Count = len(UKUn_SWL_df['S. No.'])
UKUnSW_Percent = round(UKUn_SWL_Count / UKUn_Count * 100,2)
UKUn_SPIN_Count = len(UKUn_SPIN_df['S. No.'])
UKUnSP_Percent = round(UKUn_SPIN_Count / UKUn_Count * 100,2)

print(f"Total Unemployed: {UKUn_Count}")
print(f"Total Male Unemployed: {UKUnM_Count}")
print(f"Total Female Unemployed: {UKUnF_Count}")
print(f"Total Other Unemployed: {UKUnO_Count}")
print(f"Total Unemployed GAD Count: {UKUn_GAD_Count}  /  {UKUnG_Percent}%")
print(f"Total Unemployed SWL Count: {UKUn_SWL_Count}  /  {UKUnSW_Percent}%")
print(f"Total Unemployed SPIN Count: {UKUn_SPIN_Count}  /  {UKUnSP_Percent}%")

Total Unemployed: 120
Total Male Unemployed: 106
Total Female Unemployed: 14
Total Other Unemployed: 0
Total Unemployed GAD Count: 38  /  31.67%
Total Unemployed SWL Count: 94  /  78.33%
Total Unemployed SPIN Count: 68  /  56.67%

In [109]:
#Employed
UKEm_GAD_df = UKfunEmp_df.loc[UKfunEmp_df['GAD_T'] > 9]
UKEm_SWL_df = UKfunEmp_df.loc[UKfunEmp_df['SWL_T'] < 20]
UKEm_SPIN_df = UKfunEmp_df.loc[UKfunEmp_df['SPIN_T'] > 19]
UKEmMale = UKfunEmp_df.loc[UKfunEmp_df['Gender'] == "Male"]
UKEmFemale = UKfunEmp_df.loc[UKfunEmp_df['Gender'] == "Female"]
UKEmOther = UKfunEmp_df.loc[UKfunEmp_df['Gender'] == "Other"]

UKEm_Count = len(UKfunEmp_df['S. No.'])
UKEmM_Count = len(UKEmMale['S. No.'])
UKEmF_Count = len(UKEmFemale['S. No.'])
UKEmO_Count = len(UKEmOther['S. No.'])
UKEm_GAD_Count = len(UKEm_GAD_df['S. No.'])
UKEmG_Percent = round(UKEm_GAD_Count / UKEm_Count * 100,2)
UKEm_SWL_Count = len(UKEm_SWL_df['S. No.'])
UKEmSW_Percent = round(UKEm_SWL_Count / UKEm_Count * 100,2)
UKEm_SPIN_Count = len(UKEm_SPIN_df['S. No.'])
UKEmSP_Percent = round(UKEm_SPIN_Count / UKEm_Count * 100,2)

print(f"Total Employed: {UKEm_Count}")
print(f"Total Male Employed: {UKEmM_Count}")
print(f"Total Female Employed: {UKEmF_Count}")
print(f"Total Other Employed: {UKEmO_Count}")
print(f"Total Employed GAD Count: {UKEm_GAD_Count}  /  {UKEmG_Percent}%")
print(f"Total Employed SWL Count: {UKEm_SWL_Count}  /  {UKEmSW_Percent}%")
print(f"Total Employed SPIN Count: {UKEm_SPIN_Count}  /  {UKEmSP_Percent}%")

Total Employed: 237
Total Male Employed: 225
Total Female Employed: 11
Total Other Employed: 1
Total Employed GAD Count: 37  /  15.61%
Total Employed SWL Count: 115  /  48.52%
Total Employed SPIN Count: 97  /  40.93%

In [110]:
#Uni Student
UKSt_GAD_df = UKfunUni_df.loc[UKfunUni_df['GAD_T'] > 9]
UKSt_SWL_df = UKfunUni_df.loc[UKfunUni_df['SWL_T'] < 20]
UKSt_SPIN_df = UKfunUni_df.loc[UKfunUni_df['SPIN_T'] > 19]
UKStMale = UKfunUni_df.loc[UKfunUni_df['Gender'] == "Male"]
UKStFemale = UKfunUni_df.loc[UKfunUni_df['Gender'] == "Female"]
UKStOther = UKfunUni_df.loc[UKfunUni_df['Gender'] == "Other"]

UKSt_Count = len(UKfunUni_df['S. No.'])
UKStM_Count = len(UKStMale['S. No.'])
UKStF_Count = len(UKStFemale['S. No.'])
UKStO_Count = len(UKStOther['S. No.'])
UKSt_GAD_Count = len(UKSt_GAD_df['S. No.'])
UKStG_Percent = round(UKSt_GAD_Count / UKSt_Count * 100,2)
UKSt_SWL_Count = len(UKSt_SWL_df['S. No.'])
UKStSW_Percent = round(UKSt_SWL_Count / UKSt_Count * 100,2)
UKSt_SPIN_Count = len(UKSt_SPIN_df['S. No.'])
UKStSP_Percent = round(UKSt_SPIN_Count / UKSt_Count * 100,2)

print(f"Total Uni Student: {UKSt_Count}")
print(f"Total Male Employed: {UKStM_Count}")
print(f"Total Female Employed: {UKStF_Count}")
print(f"Total Other Employed: {UKStO_Count}")
print(f"Total Uni Student GAD Count: {UKSt_GAD_Count}  /  {UKStG_Percent}%")
print(f"Total Uni Student SWL Count: {UKSt_SWL_Count}  /  {UKStSW_Percent}%")
print(f"Total Uni Student SPIN Count: {UKSt_SPIN_Count}  /  {UKStSP_Percent}%")

Total Uni Student: 481
Total Male Employed: 450
Total Female Employed: 28
Total Other Employed: 3
Total Uni Student GAD Count: 90  /  18.71%
Total Uni Student SWL Count: 227  /  47.19%
Total Uni Student SPIN Count: 220  /  45.74%

In [119]:
#USA Totals
print("USA")
print("---------------------------")
print(f"Surveyed gamers who play for fun:  {funT_Count}")
print(f"    Male: {funM_Count}")   
print(f"    Female: {funF_Count}")  
print(f"    Other: {funO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {GAD_Count} ({G_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {SWL_Count} ({SW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {SPIN_Count} ({SP_Percent}%)")
print("---------------------------")
print(f"Total Unemployed: {Un_Count}")
print(f"    Male: {UnM_Count}")
print(f"    Female: {UnF_Count}")
print(f"    Other: {UnO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {Un_GAD_Count} ({UnG_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {Un_SWL_Count} ({UnSW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {Un_SPIN_Count} ({UnSP_Percent}%)")
print("---------------------------")
print(f"Total Employed: {Em_Count}")
print(f"    Male: {EmM_Count}")
print(f"    Female: {EmF_Count}")
print(f"    Other: {EmO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {Em_GAD_Count} ({EmG_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {Em_SWL_Count} ({EmSW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {Em_SPIN_Count} ({EmSP_Percent}%)")
print("---------------------------")
print(f"Total Uni Student: {St_Count}")
print(f"  Male: {StM_Count}")
print(f"  Female: {StF_Count}")
print(f"  Other: {StO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {St_GAD_Count} ({StG_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {St_SWL_Count} ({StSW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {St_SPIN_Count} ({StSP_Percent}%)")
print("---------------------------")

USA
---------------------------
Surveyed gamers who play for fun:  4131
    Male: 3826
    Female: 285
    Other: 20
...
  Further GAD Eval Recommended:  740 (17.91%)
  Dissatisfaction with Life based on SWL Scale:  1828 (44.25%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  1716 (41.54%)
---------------------------
Total Unemployed: 335
    Male: 304
    Female: 28
    Other: 3
...
  Further GAD Eval Recommended:  82 (24.48%)
  Dissatisfaction with Life based on SWL Scale:  251 (74.93%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  158 (47.16%)
---------------------------
Total Employed: 1047
    Male: 962
    Female: 82
    Other: 3
...
  Further GAD Eval Recommended:  143 (13.66%)
  Dissatisfaction with Life based on SWL Scale:  426 (40.69%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  350 (33.43%)
---------------------------
Total Uni Student: 2083
  Male: 1935
  Female: 137
  Other: 11
...
  Further GAD Eval Recommended:  399 (19.16%)
  Dissatisfaction with Life based on SWL Scale:  893 (42.87%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  895 (42.97%)
---------------------------

In [116]:
#Germany Totals
print("Germany")
print("---------------------------")
print(f"Surveyed gamers who play for fun: {GerfunT_Count}")
print(f"    Male: {GerfunM_Count}")   
print(f"    Female: {GerfunF_Count}")  
print(f"    Other: {GerfunO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {GerGAD_Count} ({GerG_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {GerSWL_Count} ({GerSW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {GerSPIN_Count} ({GerSP_Percent}%)")
print("---------------------------")
print(f"Total Unemployed: {GerUn_Count}")
print(f"    Male: {GerUnM_Count}")
print(f"    Female: {GerUnF_Count}")
print(f"    Other: {GerUnO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {GerUn_GAD_Count} ({GerUnG_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {GerUn_SWL_Count} ({GerUnSW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {GerUn_SPIN_Count} ({GerUnSP_Percent}%)")
print("---------------------------")
print(f"Total Employed: {GerEm_Count}")
print(f"    Male: {GerEmM_Count}")
print(f"    Female: {GerEmF_Count}")
print(f"    Other: {GerEmO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {GerEm_GAD_Count} ({GerEmG_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {GerEm_SWL_Count} ({GerEmSW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {GerEm_SPIN_Count} ({GerEmSP_Percent}%)")
print("---------------------------")
print(f"Total Uni Student: {GerSt_Count}")
print(f"  Male: {GerStM_Count}")
print(f"  Female: {GerStF_Count}")
print(f"  Other: {GerStO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {GerSt_GAD_Count} ({GerStG_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {GerSt_SWL_Count} ({GerStSW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {GerSt_SPIN_Count} ({GerStSP_Percent}%)")
print("---------------------------")

Germany
---------------------------
Surveyed gamers who play for fun: 1279
    Male: 1228
    Female: 50
    Other: 1
...
  Further GAD Eval Recommended:  174 (13.6%)
  Dissatisfaction with Life based on SWL Scale:  584 (45.66%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  489 (38.23%)
---------------------------
Total Unemployed: 100
    Male: 93
    Female: 7
    Other: 0
...
  Further GAD Eval Recommended:  20 (20.0%)
  Dissatisfaction with Life based on SWL Scale:  81 (81.0%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  47 (47.0%)
---------------------------
Total Employed: 216
    Male: 208
    Female: 8
    Other: 0
...
  Further GAD Eval Recommended:  24 (11.11%)
  Dissatisfaction with Life based on SWL Scale:  90 (41.67%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  68 (31.48%)
---------------------------
Total Uni Student: 673
  Male: 648
  Female: 24
  Other: 1
...
  Further GAD Eval Recommended:  74 (11.0%)
  Dissatisfaction with Life based on SWL Scale:  284 (42.2%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  248 (36.85%)
---------------------------

In [117]:
#UK Totals
#Germany Totals
print("UK")
print("---------------------------")
print(f"Surveyed gamers who play for fun: {UKfunT_Count}")
print(f"    Male: {UKfunM_Count}")   
print(f"    Female: {UKfunF_Count}")  
print(f"    Other: {UKfunO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {UKGAD_Count} ({UKG_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {UKSWL_Count} ({UKSW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {UKSPIN_Count} ({UKSP_Percent}%)")
print("---------------------------")
print(f"Total Unemployed: {UKUn_Count}")
print(f"    Male: {UKUnM_Count}")
print(f"    Female: {UKUnF_Count}")
print(f"    Other: {UKUnO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {UKUn_GAD_Count} ({UKUnG_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {UKUn_SWL_Count} ({UKUnSW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {UKUn_SPIN_Count} ({UKUnSP_Percent}%)")
print("---------------------------")
print(f"Total Employed: {UKEm_Count}")
print(f"    Male: {UKEmM_Count}")
print(f"    Female: {UKEmF_Count}")
print(f"    Other: {UKEmO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {UKEm_GAD_Count} ({UKEmG_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {UKEm_SWL_Count} ({UKEmSW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {UKEm_SPIN_Count} ({UKEmSP_Percent}%)")
print("---------------------------")
print(f"Total Uni Student: {UKSt_Count}")
print(f"  Male: {UKStM_Count}")
print(f"  Female: {UKStF_Count}")
print(f"  Other: {UKStO_Count}")
print("...")
print(f"  Further GAD Eval Recommended:  {UKSt_GAD_Count} ({UKStG_Percent}%)")
print(f"  Dissatisfaction with Life based on SWL Scale:  {UKSt_SWL_Count} ({UKStSW_Percent}%)")
print(f"  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  {UKSt_SPIN_Count} ({UKStSP_Percent}%)")
print("---------------------------")

UK
---------------------------
Surveyed gamers who play for fun: 931
    Male: 869
    Female: 56
    Other: 6
...
  Further GAD Eval Recommended:  190 (20.41%)
  Dissatisfaction with Life based on SWL Scale:  482 (51.77%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  433 (46.51%)
---------------------------
Total Unemployed: 120
    Male: 106
    Female: 14
    Other: 0
...
  Further GAD Eval Recommended:  38 (31.67%)
  Dissatisfaction with Life based on SWL Scale:  94 (78.33%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  68 (56.67%)
---------------------------
Total Employed: 237
    Male: 225
    Female: 11
    Other: 1
...
  Further GAD Eval Recommended:  37 (15.61%)
  Dissatisfaction with Life based on SWL Scale:  115 (48.52%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  97 (40.93%)
---------------------------
Total Uni Student: 481
  Male: 450
  Female: 28
  Other: 3
...
  Further GAD Eval Recommended:  90 (18.71%)
  Dissatisfaction with Life based on SWL Scale:  227 (47.19%)
  Suggests Diagnosis of Social Anxiety Disorder based on SPIN Test:  220 (45.74%)
---------------------------